version: "3.7"
services:
  raffle_frontend:
    container_name: raffle_frontend
    image : abdibasid1/raffle:latest
    build: ./raffle
    ports:
    - target: 5000
      published: 5000
  number_backend:
    container_name: SFIA2_number
    image : abdibasid1/number:latest
    build: ./number
  prize_backend:
    container_name: SFIA2_prize
    image : abdibasid1/prize:latest
    build: ./prize
  winner_backend:
    container_name: SFIA2_winner
    image : abdibasid1/winner:latest
    build: ./winner
  



          


